# Generated by Django 5.2.6 on 2025-09-09 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('max_score', models.IntegerField(default=10)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='FinalAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lecturer_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('final_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade', models.CharField(max_length=2)),
                ('comments', models.TextField(blank=True)),
                ('assessed_date', models.DateTimeField(auto_now_add=True)),
                ('assessed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('attachment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_assessment', to='attachments.attachment')),
            ],
        ),
        migrations.CreateModel(
            name='LecturerEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_scores', models.JSONField()),
                ('overall_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comments', models.TextField()),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_evaluation', to='attachments.attachment')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_lecturer_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_scores', models.JSONField()),
                ('overall_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comments', models.TextField()),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_evaluation', to='attachments.attachment')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
