# Generated by Django 5.2.7 on 2025-10-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='year_of_study',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
