# Generated by Django 5.2.6 on 2025-09-15 14:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('supervisor_name', models.CharField(max_length=100)),
                ('supervisor_email', models.EmailField(blank=True, max_length=254)),
                ('supervisor_phone', models.CharField(blank=True, max_length=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to=settings.AUTH_USER_MODEL)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attachments.industry')),
            ],
        ),
        migrations.CreateModel(
            name='LogbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('department_section', models.CharField(help_text='Department or section where you worked today', max_length=100)),
                ('tasks', models.TextField(help_text='Tasks you worked on today')),
                ('skills_learned', models.TextField(help_text='New skills or knowledge gained')),
                ('achievements', models.TextField(blank=True, help_text='Notable achievements or accomplishments')),
                ('challenges', models.TextField(blank=True, help_text='Challenges faced and how you addressed them')),
                ('hours_worked', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(24)])),
                ('supervisor_comments', models.TextField(blank=True)),
                ('edit_count', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logbook_entries', to='attachments.attachment')),
            ],
            options={
                'ordering': ['-entry_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.UniqueConstraint(fields=('student',), name='unique_student_attachment'),
        ),
        migrations.AlterUniqueTogether(
            name='logbookentry',
            unique_together={('attachment', 'entry_date')},
        ),
    ]
