# Generated by Django 5.2.6 on 2025-09-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
