# Generated by Django 5.2.7 on 2025-10-05 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_alter_department_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='placement_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='attachments.placementformsubmission'),
        ),
    ]
