# Generated by Django 5.2.7 on 2025-10-07 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0003_alter_studentassignment_placement_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='university',
            field=models.CharField(default='Machakos University', max_length=200),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('duration_years', models.IntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='attachments.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
