# Generated by Django 5.2.7 on 2025-10-08 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0004_department_university_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='placement_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='attachments.placementformsubmission'),
        ),
    ]
